---
abstract: 'separate aggregated parameters for functions'
author:
  - 'The Smithsonian Astrophysical Observatory'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Hash::Util: 0
  Storable: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Params-Validate-Aggregated
no_index:
  directory:
    - inc
    - t
requires:
  Data::Alias: 0
  Params::Validate: 0
resources:
  license: http://opensource.org/licenses/gpl-license.php
version: 0.03
